//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreDesktopClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookstoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookstoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookstoreDesktopClient.Resources.BookstoreResources", typeof(BookstoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookstore.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of book title to buy..
        /// </summary>
        public static string BookPurchaseForm_BookTitle_DESCRIPTION {
            get {
                return ResourceManager.GetString("BookPurchaseForm_BookTitle_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter book title: .
        /// </summary>
        public static string BookPurchaseForm_BookTitle_TITLE {
            get {
                return ResourceManager.GetString("BookPurchaseForm_BookTitle_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Title.
        /// </summary>
        public static string BookPurchaseForm_FORM_TITLE {
            get {
                return ResourceManager.GetString("BookPurchaseForm_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase book title.
        /// </summary>
        public static string BookPurchaseForm_PuchaseButton_DESCRIPTION {
            get {
                return ResourceManager.GetString("BookPurchaseForm_PuchaseButton_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string BookPurchaseForm_PuchaseButton_TITLE {
            get {
                return ResourceManager.GetString("BookPurchaseForm_PuchaseButton_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase of title {0} failed. Reason: {1}..
        /// </summary>
        public static string BookPurchaseResult_FAILED {
            get {
                return ResourceManager.GetString("BookPurchaseResult_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds.
        /// </summary>
        public static string BookPurchaseResult_INSUFFICIENT_FUNDS {
            get {
                return ResourceManager.GetString("BookPurchaseResult_INSUFFICIENT_FUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string BookPurchaseResult_INVALID_USER {
            get {
                return ResourceManager.GetString("BookPurchaseResult_INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold out.
        /// </summary>
        public static string BookPurchaseResult_SOLD_OUT {
            get {
                return ResourceManager.GetString("BookPurchaseResult_SOLD_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase of title {0} succeeded..
        /// </summary>
        public static string BookPurchaseResult_SUCCEEDED {
            get {
                return ResourceManager.GetString("BookPurchaseResult_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title does not exists.
        /// </summary>
        public static string BookPurchaseResult_UNKNOWN_TITLE {
            get {
                return ResourceManager.GetString("BookPurchaseResult_UNKNOWN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed.
        /// </summary>
        public static string BookPurschaseResult_REQUEST_FAILED {
            get {
                return ResourceManager.GetString("BookPurschaseResult_REQUEST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out.
        /// </summary>
        public static string BookPurschaseResult_REQUEST_TIMED_OUT {
            get {
                return ResourceManager.GetString("BookPurschaseResult_REQUEST_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ResultDialogContent_FAILURE {
            get {
                return ResourceManager.GetString("ResultDialogContent_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string ResultDialogContent_SUCCESS {
            get {
                return ResourceManager.GetString("ResultDialogContent_SUCCESS", resourceCulture);
            }
        }
    }
}
